name: organix
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  geolocator: ^7.6.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  leak_tracker: ^10.0.0
  leak_tracker_flutter_testing: ^2.0.1
  leak_tracker_testing: ^2.0.1
  lints: ^4.0.0
  material_color_utilities: ^0.8.0
  meta: ^1.11.0
  test_api: ^0.6.1
  vm_service: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/organix_logo1.png
