name: organixx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  permission_handler: ^11.3.1
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  provider: ^6.1.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  google_generative_ai: ^0.4.2
  http: ^1.2.1
  file_picker: ^8.0.3
  flutter_pdfview: ^1.3.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/organix_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/organix_logo.ico"
