// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiu1IV5tOJv5zuJlzW5XuNbBBUrr4LRQY',
    appId: '1:249666919778:web:f13b79283258741897a03b',
    messagingSenderId: '249666919778',
    projectId: 'organix-b4eab',
    authDomain: 'organix-b4eab.firebaseapp.com',
    storageBucket: 'organix-b4eab.appspot.com',
    measurementId: 'G-KCVWGFPFE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTddjcrHeQD4klwNb7miWDvt0iH5tyQI',
    appId: '1:249666919778:android:0fde57e12bb19f1097a03b',
    messagingSenderId: '249666919778',
    projectId: 'organix-b4eab',
    storageBucket: 'organix-b4eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGo-yaz0fZOlhT58DdXXUlEaP0GRh_Us',
    appId: '1:249666919778:ios:2e23b171b9821af397a03b',
    messagingSenderId: '249666919778',
    projectId: 'organix-b4eab',
    storageBucket: 'organix-b4eab.appspot.com',
    iosBundleId: 'com.example.organix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGo-yaz0fZOlhT58DdXXUlEaP0GRh_Us',
    appId: '1:249666919778:ios:2e23b171b9821af397a03b',
    messagingSenderId: '249666919778',
    projectId: 'organix-b4eab',
    storageBucket: 'organix-b4eab.appspot.com',
    iosBundleId: 'com.example.organix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiu1IV5tOJv5zuJlzW5XuNbBBUrr4LRQY',
    appId: '1:249666919778:web:1f0e84d1c27b852d97a03b',
    messagingSenderId: '249666919778',
    projectId: 'organix-b4eab',
    authDomain: 'organix-b4eab.firebaseapp.com',
    storageBucket: 'organix-b4eab.appspot.com',
    measurementId: 'G-QBGF8GL2KF',
  );
}
